### ISSUE TITLE
Wait until buffer full

### ISSUE THREAD

**Issue by bartbutenaers** [IOIO72/node-red-contrib-buffer-array#1]
Hi Tamio (@IOIO72),

I needed this weekend a quick way to calculate a 'moving average' across N successive messages, and your node made this very simple.  So thanks a lot for your contribution !!

It would be nice if you could add a **checkbox** (e.g. '_Start when buffer full'_) to the config screen.  When this checkbox is selected, the first output message is generated as soon as ALL positions in the buffer are filled.

For example if we have a buffer of length 6, and we pass the alphabet to the input:
0 0 0 0 0 **A**
0 0 0 0 **A B**
0 0 0 **A B C**
0 0 **A B C D**
0 **A B C D E**
**A B C D E F**   --> This would become the content of the first output message
**B C D E F G**
**C D E F G H**
...

P.S. Perhaps add such an example to the readme file.

Thanks in advance !!
Kind regards,

Bart Butenaers

**Comment by IOIO72** [comment]
Hi Bart,
thank you for your nice suggestion. Tomorrow I'll take a look at this.
Kind regards,
Tamio

**Comment by IOIO72** [comment]
@bartbutenaers I updated the NPM package and the GIT Repo.
I don't know how long the palette manager of Node-RED needs to deliver the new package in the search result.
I hope, the node fulfills your needs. Just let me know, if you need some other enhancements. ;)

**Comment by bartbutenaers** [comment]
Hi Tamio (@IOIO72),

Tested and works fine.  
Thanks for your very fast support !!!

Greetings from a rainy Belgium,
Bart
